### ISSUE TITLE
[please fix] MCGS v1.5.6 no building tool and town hall in supply chest!?

### ISSUE THREAD

**Issue by Werewolf74** [kreezxil/minecolonies-getting-started#1]
**Describe the bug**
Hello, there is some problem, i have first time played your mod. MCGS v1.5.6, and started 3 times new world, if i place build Supply Camp or Ship then is there no buildings tool and town hall in the supply chest!?

town hall can not be crafted so there is now way to get town hall and can not continue playing my first world cos no town hall in the supply chest and only one time can place supply camp, or how to get the town hall, that i can start with the minecolonies?

Is the problem in the MineColonies mod. and not in your mod pack then sry, tell pls that to H3lay if you have contact to him,thx.

Mfg. Werewolf

**To Reproduce**

**Screenshots**

**Versions:**

 - Minecraft:
 - Forge:
 - Mod: MCGS v.1.5.6

**Additional context**

**Comment by kreezxil** [comment]
I am aware of this error. will be fixed in todays update.

feel free to delete parts of the bug report next time that you don't have
information for.

**Comment by Werewolf74** [comment]
Describe the bug
Hello, there is some problem, i have first time played your mod. MCGS v1.5.6, and started 3 times new world, if i place build Supply Camp or Ship then is there no buildings tool and town hall in the supply chest!?

town hall can not be crafted so there is now way to get town hall and can not continue playing my first world cos no town hall in the supply chest and only one time can place supply camp, or how to get the town hall, that i can start with the minecolonies?

Edit:

The problem is in the code of MineColonies mod. and not in your mod pack, sry,.

i wrote the info but in wrong place so it was not visible,i edit the info again but you got the first one i think. sry again! :/

Mfg. Werewolf

**Comment by kreezxil** [comment]
This is fixed in MCGS 1.6.7. Please update your pack to that version. The supply chest for the ship will be to the right of the captain's bed and will contain the townhall and the placement wand.

I checked this multiple times yesterday.

**Comment by Werewolf74** [comment]
Yea i know, it`s fixed, thy for the update. ;)

Mfg. Werewolf
