### ISSUE TITLE
Lumberjack placing items into void 

### ISSUE THREAD

**Issue by Seilican** [kreezxil/minecolonies-getting-started#11]
Expected behavior
the lumberjack harvesting tree's and placing the logs and so on in the inventory of the hut

Actual behaviour
as far as i can tell the lumberjack stop's seeing the inventory of the hut block at all for anything but still come's back and drop's things into something i can't access or the void

Steps to reproduce the problem
set up a lumberjack
play for a while all works find like we want
log out
log back in to server
lumberjack is now not using same hut block as we are

**Versions:**

 - Minecraft: 1.14.4
 - Forge: 
 - Mod: minecolonies-0.10.403-ALPHA-universal.jar

**Additional context**
miner's are doing this too but longer to bug out

**Comment by kreezxil** [comment]
@Seilican is it still a thing? if this is reported on the https://github.com/ldtteam/minecolonies side I need the link for the report pasted here. thanks.

**Comment by kreezxil** [comment]
no response, so closing.
