### ISSUE TITLE
[please fix] Stuck at launcher "loading"

### ISSUE THREAD

**Issue by lulumolloy** [kreezxil/minecolonies-getting-started#15]
**Describe the bug**
I downloaded the pack and hit play. Sent to the launcher and despite a lot of fiddling around, it won't say anything but "loading" where the play button should be. It does work with the 1.12.2 version, not the 1.14.4. 

To fix, I've tried a few previous versions of the pack (still 1.14.4), had twitch repair the pack, deleted the versions from the install folder (I've been having similar issues with other packs and this always fixed it), uninstalled and reinstalled the pack.

**Screenshots**
<img width="910" alt="Screen Shot 2019-10-09 at 4 16 02 PM" src="https://user-images.githubusercontent.com/23488430/66517660-83089700-eab1-11e9-9e74-eb93f247b1e0.png">

**Versions:**
Getting started- 2.17.18 & 2.16.17
 - Minecraft: 1.14.4
 - Forge:
 - Mod:

**Comment by hellwolf95** [comment]
What's under the launcher log

**Comment by kreezxil** [comment]
@lulumolloy in the Twitch launcher global Minecraft settings, change the launcher method back to Native. That will solve your issue.

![image](https://user-images.githubusercontent.com/3880072/66584774-5903b300-eb4b-11e9-8f46-6c7469fb890b.png)

**Comment by kreezxil** [comment]
no further response from player.

will also suggest GDLauncher as an alternative https://gdevs.io/
