### ISSUE TITLE
When loading up from twitch launcher game crashes

### ISSUE THREAD

**Issue by Mrjuicie** [kreezxil/minecolonies-getting-started#17]
Version: 2.30.31

Minecraft Version: 1.14.4

(modded) forge-28.1.69

When launching the game from twitch it loads fine, but when i goto press play to load minecraft game crashes and this is what i get in the log

Failed to find Minecraft resource version 1.14.4-20190829.143755 at C:\Program Files(x86)\Minecraft\Install\libraries\net\minecraftforge\forge\1.14.4-28.1.69\forge-1.14.4-28.1.69-client.jar

**Comment by kreezxil** [comment]
the mod pack install is corrupted. that is, your copy of twitch corrupted
it. this happens from time to time. the only solution is to delete the
profile, right click it and choose "remove profile" make sure to check off
"backups" and then restart twitch and then reinstall the pack.

**Comment by Mrjuicie** [comment]
I have done this a couple times even reinstalled twitch I still get a game crash with he same error.

**Comment by Mrjuicie** [comment]
disregard it is now working, for some reason twitch didn't completely uninstall from my computer.  thank you for helping me.
