### ISSUE TITLE
NBT tag to big

### ISSUE THREAD

**Issue by Drifter107** [kreezxil/minecolonies-getting-started#18]
Internal exception io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Tried to read NBT tag that was to big: tried to allocate: 1bytes where max allowed:0

That;s when i get when trying to log onto my server or single player.
also in the server pack randompatches is for 1.12. i replaced it with a 1.14 ver an it gets loaded but doesn't fix my problem.
re-downloading an reinstalling doesn't fix it nor does deleting playerdata file.
ideas? 
Never mind.. Switching to native launcher seems to have fixed my issue!!!

**Comment by kreezxil** [comment]
Are you on the latest version of the pack? is that when this started?
Twitch might've screwed up again. Try the pack in GDLauncher from
https://gdevs.io

I'll see if I can duplicate the effort  here.

**Comment by kreezxil** [comment]
thanks for the catch on this.

I need your logs tho to track it down further.

## Steps I took to reproduce
1. delete my own copy
2. install fresh as if I were you
3. fixed server randompatches
4. connected to server
5. and well, I connected I didn't receive your issue.

Therefore let me reiterate, i need all of your logs include debug logs. please use a pasting service like https://gist.github.com or https://paste.ubuntu.com

**Comment by Drifter107** [comment]
https://gist.github.com/Drifter107/e3681871cd833d86599b42bdcfff392b

**Comment by Drifter107** [comment]
At some point after i was able to log in i added some other mods. pretty sure this is the first try log/debug. also as you well see im running a server manager thingy i did try it with out it an had same issue... i do not have those logs. also... dying seems to be a bad thing.. end up trapped inside my skin an cant move... but that is after i added a couple mods. ive got 6 more log files an 4 more debug but im not sure when i added more mods if you really want those to let me know.

**Comment by kreezxil** [comment]
remove the other mods and try again

**Comment by Drifter107** [comment]
I;m thinking you missed the part where i said switching to the native launcher fixed the nbt thing. Also i switched to the Gdlauncher shortly after... I really like those kind of launchers.. thanks for the that!!

**Comment by Drifter107** [comment]
And the mod pack is epic!!

**Comment by kreezxil** [comment]
ok, a note then, when you discover a fix. make a statement of it in the
last comment and close the comment. you don't have to wait on the developer
to do it. :)
