### ISSUE TITLE
Build requesting

### ISSUE THREAD

**Issue by Seilican** [kreezxil/minecolonies-getting-started#19]
Would you please do a update for this weekend
We vote to remove
AmbientSounds 3
Bamboo Everything (Forge)
EmbellishCraft
TrashSlot
We vote to add
https://www.curseforge.com/minecraft/mc-mods/named-areas
https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod
https://www.curseforge.com/minecraft/mc-mods/comforts
https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator
and if you need to replace simple storage 
we will some power mod to go with
https://www.curseforge.com/minecraft/mc-mods/refined-storage

**Comment by kreezxil** [comment]
closed as it is now in a new tracker
