### ISSUE TITLE
version uncompatibility

### ISSUE THREAD

**Issue by MikaelOre** [kreezxil/minecolonies-getting-started#22]
when I downloaded the "Minecolonies Getting Started
By: Kreezxil, H3lay" modpack, the launcher opened like usual, but when I clicked the play button right before fully launching it the game crashed, I tried copy+pasting the mods folder to my .minecraft and downloaded the recommended forge version to see if that worked.

after all that, this screen appeared.
![Anotación 2019-12-12 173304](https://user-images.githubusercontent.com/58832246/70758785-a8ac5980-1d09-11ea-9854-f86611a44fe4.png)

for more details here is the latest.log 
[latest.log](https://github.com/kreezxil/minecolonies-getting-started/files/3958319/latest.log)

hopefully is just my PC being dumb, but I actually don't think so for sure... still I felt like noticing you about my problem. 

so long.

**Comment by kreezxil** [comment]
This happened because you copied them to your folder. Your folder has the wrong version of forge.

The problem you initially had was that Twitch fubarred the install. This happens quite frequently and is not a fault of the pack.

Simply delete the installation and install again.

If it continues to fail. Abandon Twitch altogether and install GD Launcher from https://gdevs.io

if you need proof that the pack works I can take a video where you can see me delete the pack as I am the developer, reinstall the pack, and then play the pack.

**Comment by MikaelOre** [comment]
![Anotación 2019-12-13 135106](https://user-images.githubusercontent.com/58832246/70827811-a997c680-1daf-11ea-901c-a19f7a2d201e.png)
"This happened because you copied them to your folder. Your folder has the wrong version of forge."

Actually I used the same forge that twitch is using for the modpack, that is why I'm telling you that the problem comes from that reason, I tried deleting and reinstalling the mod pack like 12 times, even following how-to-fix tutorials but none of them worked.

I also tried the GDLauncher and I couldn't tell it solved MY problem becuase it kept stopping the installation at 99%, that means either Im very unlucky or idk...

although I it looks like a good idea watching you do what I did and somehow it worked for you, I rather look up for another solution, but even now I keep trying with both options you gave me, in the  end I might just start with the "Better Than Minecolonies" pack instead, I was trying to use the other pack first because it has quests to help me learn faster through the mods.

Sorry for the trouble, so long.


PD: nevermind... even though "Better Than Minecolonies" worked right last night, for some reason it started crashing too, I can confirm now that I am cursed.

**Comment by kreezxil** [comment]
GD Launcher doesn't support copying form Twitch instances, you'll have to install the pack fresh there.

And there are 2 issues in GD Launcher assoicated with the 99% bug. There is an issue about that that contains both solutions.

https://github.com/gorilla-devs/GDLauncher/issues/268

My suggestion is to go back to Twitch and delete the profile and then reinstall it fresh.
