### ISSUE TITLE
Colonial Age and Minecolonies Getting Started keep crashing

### ISSUE THREAD

**Issue by FrogMan69** [kreezxil/minecolonies-getting-started#25]
Hi, I've been having trouble with the Colonial Age modpack on curseforge. Whenever I click play on the minecraft launcher it closes immediately and says "An unexpected issue occurred". Here is the crash log: https://pastebin.com/JDQmeQtU
Thanks for any help
Pastebin
Crash Log - Pastebin.com

I am using Version: 2.18.52

Minecraft Version: 1.14.4

(modded) forge-28.1.113
I'm also having the same problem with Minecolonies Getting Started

**Comment by kreezxil** [comment]
First that is two separate issues, please use only one issue per ticket.

Second, the paste  you gave me is a partial, this is now how you submit a crash report. 

1. open the crash report file
2. copy all of it, not just the current view, click on "edit" menu, the "select all", then "edit" menu then "copy"
3. now open pastebin like you did before, click in the white box and hit CTRL-V or right click and choose paste.
4. now hit submit and give me the new url

There is nothing in what you felt was relevant to help you solve your problem.

Further, I recommend GD Launcher from https://gdevs.io it does a much better job of launching packs and if you have issues with it join their Discord and read their FAQ at https://github.com/gorilla-devs/GDLauncher/wiki/FAQ-Frequently-Asked-Questions
