### ISSUE TITLE
Repair button in Tetra workbench not working

### ISSUE THREAD

**Issue by MonkChampion** [kreezxil/minecolonies-getting-started#26]
Hi there, I have been experimenting with Tetra in your modpack and when I open the workbench and put a tool in, the repair button appears saying I need a tier 0 hammer and have a tier 0 hammer (I actually have a tier 2). I then press it and it dissapears, with no other GUI popping up other than a barely noticeable spot to place items, but no craft button. Not sure if this is an issue with the pack or Tetra but I'm looking for some help fixing it, 

Thanks

**Comment by kreezxil** [comment]
this is clearly a bug with tetra.

**Comment by kreezxil** [comment]
seems to be related to all these issues: https://github.com/mickelus/tetra/issues?q=is%3Aissue+repair

and all marked closed.

**Comment by MonkChampion** [comment]
Thankyou for the quick response kreezxil, I have looked through those issues and none seem to be quite the same to mine, but related indeed. Are you alright if I make a new issue there?

**Comment by kreezxil** [comment]
It's your solemn duty to do that and when you do link it back here.

**Comment by kreezxil** [comment]
In fact any pack you play, all pack devs expect that to be the case. you find the bug, you repeat bug, report it to the mod author, and bring the link back to the pack.

**Comment by MonkChampion** [comment]
Haha yes sir, I'm on it

**Comment by MonkChampion** [comment]
https://github.com/mickelus/tetra/issues/142

**Comment by kreezxil** [comment]
mickelus says it is fixed in the build that is in today's patch.

If it continues to be an issue open another ticket.
