### ISSUE TITLE
[please fix] Freez when launching the game

### ISSUE THREAD

**Issue by Nethet** [kreezxil/minecolonies-getting-started#28]
**When I launch the pack whith the twich launcher the game freezes**

**To Reproduce**
1. Go to 'the twich launcher'
2. Click on 'play'
3. Click aigain on 'play'
4. First forge will load then when the mojang logo comes with the progressbar it freezes
(and the icon of the launcher is very strange)

**Screenshots**

![Capture](https://user-images.githubusercontent.com/38501555/83914646-eac2cf00-a771-11ea-864d-486d1533894e.PNG)
 
![Capturescreen2](https://user-images.githubusercontent.com/38501555/83914669-fadaae80-a771-11ea-8c88-9455564b520d.PNG)

[https://pastebin.com/qh68rkK6](url)
latest.log (Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://myurl.me/)

**Versions:**

 - Minecraft:1.14.4
 - Forge:28.2.6
 - Mod: ???

**Additional context**
Args: "-Xmx2304m -Xms256m -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="C:\Users\Élève\Twitch\Minecraft\Instances\Minecolonies Getting Started (MCGS)" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US"

**Comment by kreezxil** [comment]
you didn't wait long enough, it's generating an animation.

**Comment by Nethet** [comment]
ah ok, sorry
