### ISSUE TITLE
[please fix] JEI jar missing from server zip

### ISSUE THREAD

**Issue by adveres** [kreezxil/minecolonies-getting-started#29]
**Describe the bug**
Unable to shift+click to craft with JEI. JEI says it must be running on the server to work.

**To Reproduce**
Click any craftable item in JEI, and you should be able to shift+click the `+` button to place items into a crafting grid.

**Screenshots**

**Versions:**

 - Minecraft: 1.14.4
 - Forge: forge-1.14.4-28.2.6
 - Mod: jei-1.14.4-6.0.0.27

**Additional context**
I think this just needs to be in the server ZIP download. It matches the version of JEI in the client pack.

https://www.curseforge.com/minecraft/mc-mods/jei/files/2847274

**Comment by adveres** [comment]
I placed `jei-1.14.4-6.0.0.27.jar` in my server's `mods` folder and verified the issue is fixed.  Please just add it to the server zip too?

Thanks!

**Comment by kreezxil** [comment]
it is a flub, it was there 2 versions ago. thank you for the report.

**Comment by kreezxil** [comment]
fixed in today's release.

**Comment by adveres** [comment]
Thank you! Really enjoying the pack so far.

**Comment by kreezxil** [comment]
glad to hear it
